### ISSUE TITLE
remove the internal user editor from bbs.exe

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1005]
Now that we have one in init, there's not really a strong reason to leave one inside of bbs.exe.  Also it's another attack vector since someone could more easily get access to it there, than could get shell access.

Thoughts?

@MarkHofmann11 @BloodStoneBBS @granitepenguin @ericpareja @fcreid @wwivsoftwareservices

**Comment by granitepenguin** [comment]
Makes sense to me.  Since we don't really need to be able to do sysop stuff remotely through the BBS anymore (ie. you are probably just going to ssh to the box outside the BBS), the fewer things we admin inside the BBS itself, the better off we'd be.

**Comment by MarkHofmann11** [comment]
Agreed!!!

**Comment by BloodStoneBBS** [comment]
Bummer!!

Being that I run my BBS in a VM that I have locked down from external access, I rely heavily on the ability to manage users via SysOp telnet session, especially when I’m at the office or on the road.

This change will require me to either change a lot on my firewall or I’ll need to RDP to my server and then to the VM or use VSphere from my other server after remote connect.

Wouldn’t it be nearly as effective to simply increase the password security?

J..

**Comment by BloodStoneBBS** [comment]
Will this also break the validate user option in the new user feedback?  Again, I know I'm probably one of the few who don't have WWIV on a stand-alone box to manage at a console and I do find the internal user editor to be useful because of this. 
As I do most of my user management via telnet, removing the internal user editor will make it more difficult for me to address any new users for potentially days to weeks later as I try and keep my home network locked down quite tightly and only allow RDP from a select set of IP's for remote management of my server.
I appear to be the only SysOp opposed but I still hope this will be reconsidered.

**Comment by granitepenguin** [comment]
I find it ironic that you are concerned about security, but are also advocating the least secure way possible to admin the system (telnet).  At least argue for keeping it in and using ssh to connect to the BBS instead of telnet (via SyncTERM).

This is still a valid concern, but we need a better way to do it in general.  Is it possible to access the init elements individually so we can put access via the BBS back in, but have only one section of code to maintain?  Maybe with the rearchitecting of init to be more of a config tool, there's a way to allow access to the config itself?

**Comment by BloodStoneBBS** [comment]
I would love to use SSH however, I have yet to find a client that will actually work. Have tried SyncTerm and Putty but neither will connect using SSH. I get the key but the WWIVserver never connects after I enter my password.

I agree, telnet is far less secure than just about anything short of yelling my password but ATM, it's the only thing I can get to work with WWIVServer. (topic for another bug report)

In any case, perhaps after all is dialed in on the security side this can be readdressed?

**Comment by granitepenguin** [comment]
putty definitely won't work; SyncTERM is the _only_ client that currently does (because of how the current implementation works).   Definitely open an issue for that one; it should work.

**Comment by wwiv** [comment]
valuser still exists ('V' from the email prompt).  If you are using it to validate users, that still works.

**Comment by wwiv** [comment]
The full user editor is a bit dangerous though, so it's better to have it removed, however you can validate a user still while logged in as sysop.  Let me know if you have any concerns still.

Thanks!

**Comment by BloodStoneBBS** [comment]
Thanks. The Validate user is the important one as long as the user is no longer online when validated.

**Comment by BloodStoneBBS** [comment]
Any chance in adding it to the WFC?


Subject: Re: [wwivbbs/wwiv] remove the internal user editor from bbs.exe (#1005)


The full user editor is a bit dangerous though, so it's better to have it removed, however you can validate a user still while logged in as sysop. Let me know if you have any concerns still.

Thanks!

**Comment by granitepenguin** [comment]
maybe, but if you have access to WFC, you have access to init so why have it in two places?

**Comment by BloodStoneBBS** [comment]
Simple, because for decades, we've been able to easily manage users from the WFC, The SysOp Menu, the Chat F-Keys, etc...  I understand the security implication of having it in the SysOp menu but why have to launch another application to simply change a users access? 

I do see that Validate user via the Email menu works and F1 still appears to work in chat and am thankful for that.

**Comment by wwiv** [comment]
I'm not putting it back since the code is awful and duplicated with init, however I'll let 'U' from call into init --user_editor (to take you to the user editor), and also make passing --user_editor to init take you straight into the user editor.

I care about the code, but there's no reason we can't still let U spawn that to keep the experience the same.

**Comment by MarkHofmann11** [comment]
My personal thoughts are there should be a way for the sysop and co-sysop
to validate and edit users directly from the BBS.  Even if it is a separate
program, but the ability to do everything remote is a great feature.

I don't want to always compare to Mystic, but one of the things I love
about the sysop features in Mystic is that I can edit 98% of the entire BBS
just from logging in.  I can edit menus, users, commands, etc.  There isn't
anything you can't do from it other than force a logout of a hung node.

**Comment by MarkHofmann11** [comment]
Sounds like the perfect compromise.  I just responded a second ago before
reading this.  Still preserving the functionality from within the BBS - but
keeping it a separate program works just fine.  I understand the need for
clean code - as mine has gotten crazy over the years.

**Comment by wwiv** [comment]
U from the WFC will now call out to init in https://github.com/wwivbbs/wwiv/commit/6857e19e07c31e2d7e55d4daf10b792550cb1a06

@BloodStoneBBS
