### ISSUE TITLE
Exporting FTN Messages Cleanup

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1037]
When replying to an FTN message in WWIV, the TO: field has the address in brackets next to the name. I think this should be removed before exporting the packet to the ftn network, so non WWIV bbses have just the username, and will work with their new mail scans.

I've added a hack that does this in my fork. Appears to work.

Also, I think the heart colour codes should be stripped from the message text.

**Comment by MarkHofmann11** [comment]
True, I battled with a similar issue a few years ago in WWIVTOSS.  It was
exporting the name - but there was an extra "blank space" at the end that
was not visible unless you viewed it using a special editor that would
display the hidden space.

That was causing "Searches for new mail" on other people's BBS systems not
find the reply (the extra space - that was not visible).  That was one of
the first things I fixed in WWIVTOSS a few years ago.

**Comment by wwiv** [comment]
apam's fork is merged into master.  Is there anything left on this bug @apamment ? or can it be closed?

**Comment by ghost** [comment]
Can be closed.

**Comment by wwiv** [comment]
Thanks!
