### ISSUE TITLE
Network2 Crashes

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#1092]
network2 crashes everytime I log off or when it does a run

[net2log.pdf](https://github.com/wwivbbs/wwiv/files/973748/net2log.pdf)
[Mail2.pdf](https://github.com/wwivbbs/wwiv/files/973750/Mail2.pdf)
[Mail.pdf](https://github.com/wwivbbs/wwiv/files/973751/Mail.pdf)
[NETWORK.pdf](https://github.com/wwivbbs/wwiv/files/973755/NETWORK.pdf)

**Comment by rdfig** [comment]
Any progress on this issue of mine.  Anytime network2.exe runs it crashes,

**Comment by wwiv** [comment]
if you have the local.net file that causes the crash -- you can try to see if it also crashes with wwivutil net dump.

Or email it to me and I'll see if I can run it under a debugger.  Or you can run network2 under a debugger (build one and run it manually) to get a stacktrace.

**Comment by askpatrickw** [comment]
I have a repo of this...  of this andit also crashes WWIVUTIL

**Comment by askpatrickw** [comment]
I have not had to get a call stack in windbg since 1997... wow. 
Where's da symbols?

0:000> kb
 # ChildEBP RetAddr  Args to Child              
00 0020f194 77cb649c 75c66a64 ffffffff c0000417 ntdll!KiFastSystemCallRet
01 0020f198 75c66a64 ffffffff c0000417 0020f1e8 ntdll!ZwTerminateProcess+0xc
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\wwiv\ucrtbase.DLL - 
02 0020f1a8 5ec43493 ffffffff c0000417 00000000 KERNELBASE!TerminateProcess+0x2c
WARNING: Stack unwind information not available. Following frames may be wrong.
03 0020f1e8 5ec4342b 77006e77 00000000 cbf8940f ucrtbase!invoke_watson+0x33
*** WARNING: Unable to verify checksum for wwivutil.exe
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for wwivutil.exe - 
04 0020f238 00fd483a 00000004 00340de0 ffffffb1 ucrtbase!invalid_parameter_noinfo+0xb
05 0020f2a0 00ffd80b 00340de0 ffffffb1 e257e29f wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x335ba
06 0020f3a4 00fcad25 00000040 e257e567 0033bb98 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::create+0x1d34b
07 0020f45c 00fcb368 e257e5e7 5ec972e8 0033bb98 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x29aa5
08 0020f4dc 00fcf853 e257e45f 5ec972e8 0033b818 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x2a0e8
09 0020f564 00fcf853 e257e4d7 5ec972e8 0020f780 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x2e5d3
0a 0020f5ec 00fcd7b7 e257e64b 5ec972e8 0032bbb8 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x2e5d3
0b 0020f770 00fcda06 e257e907 5ec972ec 0033af68 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x2c537
0c 0020f83c 00fffc87 00000004 0032bbb8 003281b0 wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::instantiate+0x2c786
0d 0020f884 76ffef8c 7ffdf000 0020f8d0 77cd367a wwivutil!cereal::detail::StaticObject<cereal::detail::PolymorphicCasters>::create+0x1f7c7
0e 0020f890 77cd367a 7ffdf000 5e741309 00000000 kernel32!BaseThreadInitThunk+0xe
0f 0020f8d0 77cd364d 00fffcfd 7ffdf000 00000000 ntdll!__RtlUserThreadStart+0x70
10 0020f8e8 00000000 00fffcfd 7ffdf000 00000000 ntdll!_RtlUserThreadStart+0x1b

**Comment by askpatrickw** [comment]
Loop in the logfile
2017-09-15 14:05:01,915 INFO  network2 version 5.2.0.2430 (Dec 30 2016, 16:52:01)
2017-09-15 14:05:01,915 INFO  network2 starting at Fri Sep 15 14:05:01 2017
2017-09-15 14:05:01,915 INFO  command line: .0 
2017-09-15 14:05:01,915 INFO  NETWORK2 for network: WWIVNet
2017-09-15 14:05:01,915 INFO  Processing: NETS\WWIVNET\local.net
2017-09-15 14:05:01,915 INFO  Processing message with type: main_type_email/0
2017-09-15 14:05:01,915 INFO  ==============================================================
2017-09-15 14:05:01,915 INFO  Processing email to user #1
2017-09-15 14:05:01,915 INFO    Title: 'WWIVNet analysis on 08/07/17'
2017-09-15 14:05:02,009 INFO      + Received Email  'WWIVNet analysis on 08/07/17'
2017-09-15 14:05:02,009 INFO  ==============================================================
2017-09-15 14:05:02,009 INFO  compression: de1

**Comment by askpatrickw** [comment]
localnet renamed to crash.net and zipped up
[crash.zip](https://github.com/wwivbbs/wwiv/files/1307800/crash.zip)

**Comment by wwiv** [comment]
Looks like the 2nd message in the packet it corrupt.

```
==============================================================================
2017-09-15 19:54:34,605 INFO  compression: de1
destination: 0@206
from:        1@1
type:        (main_type_net_info/net_info_file)
daten:       Sun Jan 15 14:29:43 2017
length:      67
compression: de1
Text:
bsbbs.com
@815 iutopia.no-ip.org
@900 storm-mt-bbs.ddns.net
```

not sure what that is, looks like a file names bsbbs.com but its' missing the encryption bytes.
