### ISSUE TITLE
Login from command line; exit at logout

### ISSUE THREAD

**Issue by billsimon** [wwivbbs/wwiv#1105]
Using WWIV for Linux, I want to run WWIV as a direct i/o door from another BBS on the same server.

I can launch the user into WWIV with the `bbs` utility, e.g. `bbs -u1` to automatically log in as user 1. But when I log off, it takes me to the waiting for caller screen. Is there a way to configure the `bbs` utility so that it exits fully on logout?

**Comment by wwiv** [comment]
If you run it using an existing socket, you can use -XT -H[file descriptor] and the -XT will cause oneuser to be true and it'll exit after one user.

otherwise there may be things that aren't right trying to use stdio since the local IO goes there now. Can you use a different socket or file handle other than 0-2?

**Comment by billsimon** [comment]
In this case there is no local IO. The user side of the BBS is to display in the terminal session, and there is no local/sysop view. I played with setting `-H3` and then doing redirection on the command line but get `Resource deadlock avoided`

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/7c163de2a4a8cb904f90c7c68737848bff133960
