### ISSUE TITLE
AutoQuote wrap-around drops characters/words past right margin

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1170]
Using AutoQuote with long messages lops off right most characters/words after prefixing with initials. Word-wrap algo needs to be fixed along with retention of WWIV colors.
Cosmetic, not trivial to fix if we want to retain WWIV ANSI/color processing in quote.
Otherwise, a rewrite of the word-wrapping routine may be in order.

**Comment by granitepenguin** [comment]
yeah, I was going to open an issue myself. Noticed the same thing while playing with my vim stuff.

It does retain _some_ colors, but not all.  It's throwing a ^C0 in after the initials rather than remembering the original color, but _does_ retain other colors inline.

I'm not seeing character drops, I'm seeing them wrapped outside of the original quote.  This is especially obvious when there are multiple levels of quoting.

**Comment by wwiv** [comment]
I redid all of this, it should be fixed now.
