### ISSUE TITLE
WWIV5TelnetServer crashes if the path in Preferences is wrong.

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#129]
1. Install WWIV into \wwiv
2. run WWIV5TelnetServer
3. Run LocalServer  
# CRASH

It should give an error and not crash.

**Comment by wwiv** [comment]
@TRI0N Can I assign this one to you?

**Comment by TRI0N** [comment]
I assigned it to me.. I'll be working on TelnetServer today.. I'm not sure why it would crash but could be due to Settings having a unused set of duplicate values that I have removed from the next release.

**Comment by wwiv** [comment]
Hey @TRI0N - any update on this?

**Comment by TRI0N** [comment]
This I believe was from before I started working on it.. I fixed that.. Since the WWIV Installation Documents walks people thru to installed to c:\wwiv the default for Telnet Server before I started working on it was c:\bbs as the default for Telnet Server, so one of the first changes I made was to make the default c:\wwiv.
