### ISSUE TITLE
New My Basic Functionality

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1296]
Hi,

I believe only GLOBAL scope is supported so far, I noticed it is saved as somescript.script.json I wondered if USER scope could be implemented just by adding the user number into the mix. so for the sysop it would be something like somescript.1.script.json

I'd also like to add a function that checks the mtime of a gfile.

Ideally I'd like have both those things so I can extend my bulletins script to check the time a bulletin was last viewed vs when it was last updated and display a *UPDATED* or something next to it.

I get that mtime of a gfile is a pretty random thing to add, I'd be happy to look at doing these things myself, just wanted to check if you were interested in such functionality.

**Comment by wwiv** [comment]
Yup, that's about what I was planning on doing for the USER scope, looks like I just never got to it.

For the mtime, it would make sense to have a file api that has limited abilities. I worry about the scripts being injected somehow and then malicious.   GFILE seems safe for a dir, as does possibly temp,  Not sure what else would. Let me see if there's some api shape that looks like it'd be a good fit to implement here,.

**Comment by wwiv** [comment]
https://www.thevbprogrammer.com/Ch06/06-09-FSO.htm looks promising

**Comment by ghost** [comment]
I suppose if you're worried about people messing up the BBS / filesystem, you could have a sandbox directory, where scripts have full access, but no access anywhere else, sort of like a chroot for scripts?

**Comment by wwiv** [comment]
Looked into the usernum bit a little, since that data isn't available in the context for basic to use it, the change is surprisingly larger than I would have expected and not likely to be easily cherry pickable into 5.5 (for the changes outside of the bbs).  you can pull in the changes into wwiv_data.cpp for supporting "USER" vs .GLOBAL and then just use a()->usernum (ignoring the separation I try to make) to hard code the usernum.  That'll let you make progress.

Ditto for the filesystem API, that may be backportable to 5.5.

Also I don't expect to go 18 months between releases again, since most folks move from release to release vs. nightly builds I think I'll try to do smaller releases more frequently (every 3-6 months likely).

**Comment by wwiv** [comment]
Thinking something like this, wdyt?

# wwiv file api

package: wwiv.file

## Open File
wwiv.file.open(SECTION, NAME)
- section is one of:
  - "GFILES": anything allowed
  - "MENU": any *.ans, *.msg, *.b&w allowed 
- name is filename
- returns value a wwiv.file.handle.

## Read lines of a file into collection.

l = list()
wwiv.file.readlines(handle, l)
- reads all of the lines from handle into l

## Get file info
info = wwiv.file.info(handle);
- returns  wwiv file info.

## Use file info
t = info.last_modified()
- returns the last modified time as a unix time_t value

**Comment by ghost** [comment]
Looks good to me

**Comment by wwiv** [comment]
cool. If you have suggestions please feel free to let me know.

I'll start a doc on wiki or something with a bit more of the API.  The canonical "OPEN "FOO" as #1" won't work without major changes to add keywords into wwivbasic's my_basic, also I do want a more constrained set of functions.

**Comment by wwiv** [comment]
It's in 5.6 as of tonight. Here's an example:

```
l2 = list()
h2 = wwiv.io.file.open(o, "logon.msg", "R")
lm = wwiv.io.file.last_modified(h2)

print "last modified: (time_t time) "
print lm

print "last modified: (friendly time)"
print wwiv.time.format(lm, "%Y-%m-%d %H:%M:%S")
```
