### ISSUE TITLE
Add multiple logon script functions to wwiv.ini

### ISSUE THREAD

**Issue by the-godfather-007** [wwivbbs/wwiv#1304]
I may be writing it incorrectly within wwiv.ini, but would love to see the ability to have more then 1 logon/off scripts added directly to wwiv.ini so that batch files and scripts could be loaded in the order the sysop desires.

LOGON_CMD1=c:\wwiv\directory\batchfilename.bat
LOGON_CMD2=@basic:choiceofscript.bas

While I do realize that multiple scripts can be added within a single .bas file, I can't seem to get a batch file to run within that script and/or prior to.  The purpose would be, as example, to allow curl.exe to pull an ansi file, copy to g-files, to use for the following script to load.

If the possibility exists, the instructions within WWIV documentation refers to WWIV.INI as well documented, however WWIV.INI does not define this functionality.

**Comment by wwiv** [comment]
I think adding something like this to wwivbasic would be better:
```
wwiv.exec("BBS", "c:\wwiv\directory\batchfilename.bat")
```

it's a pain with INI files to enumerate that way

**Comment by the-godfather-007** [comment]
-->Thank you, I didn’t know the syntax, using a .bas file is totally fine.

**Comment by DougCooper0612** [comment]
Hey Rush, Can you tell me what setting I may not have on based on the log below? C:\wwiv>networkb --send --net=2 --node=71:1/100networkb [5.5.1.development] for network: scinet2020-10-31 14:55:38,692 INFO  BinkP send to: 71:1/1002020-10-31 14:55:38,736 INFO  wwivnet_node_number_from_ftn_address: '71:1/100'2020-10-31 14:55:38,737 INFO  session id:  in-16041705382020-10-31 14:55:38,842 INFO  OPT line: 'CRAM-MD5-797571a071be85fc964d6c1cca4fd5ee'2020-10-31 14:55:38,843 INFO         CRAM Requested by Remote Side.2020-10-31 14:55:38,843 INFO  Remote Side: Diskshop BBS2020-10-31 14:55:38,844 INFO  Remote Side: binkd/1.1a-111/Linux binkp/1.12020-10-31 14:55:38,844 INFO  BinkConfig::receive_dir: c:\wwiv\scinet\in-16041705382020-10-31 14:55:40,948 INFO  SEND:  M_NUL: WWIVVER 5.5.1.development (Oct 30 2020, 11:16:47)2020-10-31 14:55:40,950 INFO  SEND:  M_NUL: SYS The Ruins2020-10-31 14:55:40,950 INFO  SEND:  M_NUL: ZYZ The Godfather2020-10-31 14:55:40,951 INFO  SEND:  M_NUL: VER networkb/5.5.1.development binkp/1.02020-10-31 14:55:40,952 INFO  SEND:  M_NUL: LOC Unknown2020-10-31 14:55:40,952 INFO  SEND:  M_ADR: 71:1/1532020-10-31 14:55:41,166 INFO  SEND:  M_PWD: ********2020-10-31 14:55:41,282 INFO  OPT line: 'EXTCMD GZ BZ2'2020-10-31 14:55:41,283 INFO         Unknown OPT: 'EXTCMD'2020-10-31 14:55:41,284 INFO         Unknown OPT: 'GZ'2020-10-31 14:55:41,284 INFO         Unknown OPT: 'BZ2'2020-10-31 14:55:41,385 INFO  SEND:  M_ERR: Error (NETWORKB-0001): Unexpected Addresses: ' 1:229/101@fidonet 1:12/0@fidonet 1:12/1@fidonet 911:1905/0@zeronet 911:1905/1@zeronet 21:4/154@fsxnet 39:905/0@amiganet 39:905/100@amiganet 46:10/103@agoranet 77:77/0@scinet 77:1/0@scinet 77:2/0@scinet 77:3/0@scinet 77:1/100@scinet'; expected: '71:1/100'2020-10-31 14:55:41,502 ERROR STATE: FatalErrornetworkc [5.5.1.development] for network: scinetnetworkf.exe [5.5.1.development] for network: scinet2020-10-31 14:55:44,848 INFO  BinkConfig::receive_dir: c:\wwiv\scinet\in-16041705382020-10-31 14:55:44,871 INFO  Normal Exit Sent from Mail for Windows 10 From: RushfanSent: Saturday, October 31, 2020 12:01 PMTo: wwivbbs/wwivCc: DougCooper0612; AuthorSubject: Re: [wwivbbs/wwiv] Add multiple logon script functions to wwiv.ini (#1304) I think adding something like this to wwivbasic would be better:wwiv.exec("BBS", "c:\wwiv\directory\batchfilename.bat")it's a pain with INI files to enumerate that way—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by DougCooper0612** [comment]
That doesn’t work, fyi .. here’s the line I need to add…. wwiv.exec("BBS", "c:\mystic\themes\default\scripts\curl.exe http://absinthebbs.net/ctracker_cnet.ans -o c:\wwiv\gfiles\bulletin0.ans") Sent from Mail for Windows 10 From: RushfanSent: Saturday, October 31, 2020 12:01 PMTo: wwivbbs/wwivCc: DougCooper0612; AuthorSubject: Re: [wwivbbs/wwiv] Add multiple logon script functions to wwiv.ini (#1304) I think adding something like this to wwivbasic would be better:wwiv.exec("BBS", "c:\wwiv\directory\batchfilename.bat")it's a pain with INI files to enumerate that way—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by the-godfather-007** [comment]
That doesn’t work, fyi .. here’s the line I need to add….

wwiv.exec("BBS", "c:\mystic\themes\default\scripts\curl.exe http://absinthebbs.net/ctracker_cnet.ans -o c:\wwiv\gfiles\bulletin0.ans")

**Comment by wwiv** [comment]
WWIVbasic can do this now with https://github.com/wwivbbs/wwiv/commit/60d6b5b55d0fdd114804e305286bd25e93a70d01

It'd be something like this:
```
opt = wwiv.os.exec_options("DOOR32", "BBS", "chain.txt")
wwiv.os.exec(opt, ""c:\mystic\themes\default\scripts\curl.exe http://absinthebbs.net/ctracker_cnet.ans -o c:\wwiv\gfiles\bulletin0.ans")
```
