### ISSUE TITLE
Win32 b3371 NTVDM crash when trying to delete an email message

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1326]
Granted, the message is several years old but...
when reading the message I see this at the bottom:
2020-12-23 13:54:36,441 ERROR Out of bounds at Networks::at: 15>= size: 2

Then when deleting:
Delete this message? Yes
2020-12-23 13:55:14,168 FATAL Failed Precondition: at ..\core\file.cpp:285 Condition: File::IsFileHandleValid(handle_)

Edited to add:
This is from WFC console. Will try from remote terminal.

Same results using remote.

**Comment by wwiv** [comment]
any chance you can get this under the visual studio debugger to get a stack trace to help figure out where?  The 1st one makes me think the message came from a network number that no longer exists (we can fix that). Not sure on the 2nd.

**Comment by BloodStoneBBS** [comment]
I’ll see if I can get VS installed. Had some issues with my M$ account.

The message is a VERY old (June 28, 2011) email from Mark. On your hunch below, I tried “A” to reply and see this:

Unknown system number.
No mail sent.


That makes sense!

Will see if I can get that M$ account reset so I can install VS.
Any specific packages I should install?

**Comment by BloodStoneBBS** [comment]
Not a lot of info here but maybe it can help?
Unhandled exception at 0x74DAEFBB (ucrtbase.dll) in bbs.exe: Fatal program exit requested.

Looking at the message, it apparently pre-dates our current revision of WWIVnet. Probably from the WWIVSNnet that Eli was running. Mark would have had a different node number and network then.

Do you suppose this simply needs to be manually deleted somehow?

**Comment by BloodStoneBBS** [comment]
Any quick fix for the Ninja error of not being supported on x86? (after VS19 install)

**Comment by wwiv** [comment]
For the ninja issue you need to get an old copy of it and copy it over the new one.  There is no fix as MS refuses to admit it 's a problem

**Comment by wwiv** [comment]
Also I may have a way to get a stacktrace, will include it when I merge in the config.json support.  Hold tight on this one.

Also will add a wwivutil command to dump and delete emails, that seems useful, so please let's keep this around. I'm almost done with the config.json supprt (seems to work well for me and I've upgraded a dozen times now)

**Comment by BloodStoneBBS** [comment]
Thank you!

AnY particular version?

**Comment by BloodStoneBBS** [comment]
Perfect! Thank you.  I’ll give that one a try.

**Comment by fcreid** [comment]
The older 32-bit Ninja worked for me, and I can now finally build on the same 32-bit platform where I run the BBS! Thanks!

**Comment by wwiv** [comment]
3376 should have some more debugging details, would you please give that a try.

Also it turns out there are a few places where you can delete an email. Where are you in thebbs what commands did you use to get to where you deleted the email.  Also how far away was the Networks::at error log?  I'm trying to find where in the code you are getting these, so need a bit more details from you to help find it.

Thanks,

**Comment by wwiv** [comment]
Also 3377 has a wwivutil email dump command, please use that to dump the email number that is causing the problem and send that text output to me (in addition to trying again with 3377 (or 3376) and also providing some more details on where in the bbs the attempt to delete the email occurrs).

Thanks

**Comment by BloodStoneBBS** [comment]
Dang Defender... 

![image](https://user-images.githubusercontent.com/13243281/104127598-db16f480-5317-11eb-9b7d-65d23268735e.png)

Will try again.

**Comment by wwiv** [comment]
Just unzip wwivutil out of it then

**Comment by BloodStoneBBS** [comment]
Done...  So, I tried deleting normally and received the NTVDM crash but then tried to forward to myself and delete. Also crashed (ntvdm) but the message was deleted.

**Comment by BloodStoneBBS** [comment]
755FEFBB  int         29h

**Comment by wwiv** [comment]
somehting is strange, since there is no dos code in the bbs deleting a message, so there should be no ntvdm error.  in29 is a dos  interrupt for writing a character to the screen, there has to be something that wwiv is configured to execute here that is causing hte ntvdm crash.  Any ideas what that can be?

I'm also confused what steps were taking, sorry, hard for me to parse.

**Comment by BloodStoneBBS** [comment]
Not a clue..  AT least I was able to see that the message was from Mark, #1 @ 11 from either wwivsn or maybe just after he got the OK to resurrect wwivnet.  Regardless, the issue is moot now that the message has been deleted.  Ah!  Could it be a read notification?

**Comment by wwiv** [comment]
not sure what wwiv could be running, but int29 is a DOS command, so it's likely something. Look in wwiv.ini? Also I seem to remember in some other log deXXX.exe was run, please get rid of those (I'd zip them up and delete the EXE) in the network dir, we don't use DE anymore at the moment since that is DOS, maybe that is it.  Likely some binary in the network directory.

**Comment by wwiv** [comment]
Closing since the message is deleted and NTVDM error is coming from something being executed.
