### ISSUE TITLE
ENTER does not work for Next Page in Sub List (*)

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#134]
I checked this on @1, @2, @255, @70.

When you get a list of all the subs in a conference it will say [ENTER] for next page. Enter does not work, but N does.

**Comment by ericpareja** [comment]
Conference stuff is screwy. Needs an overhaul. Will try to fix this, but need to rethink the UI for this.

**Comment by BloodStoneBBS** [comment]
Regarding subslist,cpp.  Actually any key other than [Enter] [Q] or [J] will take you to the next page. Just not specifically [Enter] . Would changing some code near line 295 help with this? The current code seems to allow for any undefined key to advance but does not define the [Enter] key. ?? And how would you change this to accept carriage return?  if (wwiv::strings::IsEquals(ss, " ") lose the space?
And if so, would this also work to fix the problem where any other key works?

**Comment by askpatrickw** [comment]
You could also just change the display text so it says press N for next. ;-)

**Comment by BloodStoneBBS** [comment]
I've been thinking the same thing but dirlist works with the Enter. I'm actually sitting through several C training videos just to figure out - why - ;-)

**Comment by askpatrickw** [comment]
Hey if its a fun way to learn, knock yourself out ! ;-)

**Comment by BloodStoneBBS** [comment]
After looking into this and learning a little more about strings vs char, maybe Patrick is on to something. Rather than change the way the program looks for the input, changing the option to "N" for next page does sound like a more reasonable option at this time. Unless there is an easy way to loop it such that the action waits for either the char for enter or string entry for other options that I am totally oblivious to (very likely)

**Comment by wwiv** [comment]
I changed the display to say press "N" for next a while ago.
