### ISSUE TITLE
Importing large emails from FTN not working right.

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1395]
If I request a list of FTN subs via Areafix from my uplink, if it's a long list (as in all the Fidonet echos), I get a partial list that says "Continued in next message", but I never get that next message.
I was running a net connect after requesting one today, and the first half of the list went through as email, the second half just got displayed on the screen.

Don't know if that's an issue with the network software, or the way the uplink is sending them.

**Comment by MorgulWWIV** [comment]
OK, follow up, I went back and looked at what was printed, and there was a message during processing.  
2021-02-24 17:53:36,399 INFO  Imported FTN Email 'List of Available Areas' to 'Morgul'
2021-02-24 17:53:36,425 ERROR Skipping duplicate FTN message: 'List of Available Areas' msgid: ()

So apparently it's thinking the second half is a duplicate message, and skipping it.  This occurred while processing the incoming packets right after a net callout.

**Comment by wwiv** [comment]
If you can get a copy of those messages somehow that'd be awesome (try again, maybe rename networkf to foo so binkp can't run it to process this).

It's likely hitting the header's matching on those two messages since there is no MSGID.
Here's the fields I put into the header crc:

std::ostringstream s;
  s << msg.nh.orig_net << "/" << msg.nh.orig_node << "\r\n";
  s << msg.nh.dest_net << "/" << msg.nh.dest_node << "\r\n";
  s << msg.vh.date_time << "\r\n";
  s << msg.vh.from_user_name << "\r\n";
  s << msg.vh.subject << "\r\n";
  s << msg.vh.to_user_name << "\r\n";

// create crc32 on s

**Comment by wwiv** [comment]
Hmm.. Actually since it's not an echo mail, I likely shouldn't be checking for dupes anyway.  Thoughts?

**Comment by MorgulWWIV** [comment]
Just emailed you the packet.
