### ISSUE TITLE
When city/state/zip is required and missing, ask for zip code first.

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1418]
Since that can populate the others, start with country and then zip

(this happens with the new sysop install, since we don't fill that in at account creation time, the bbs asks on the first time the sysop logs in)

**Comment by MorgulWWIV** [comment]
Question on this.  From your comment "Since that can populate others...", it sounds like the BBS can use the zipcode to automatically get the city and state.  Is that what you meant?
If so, it's not doing it on mine.

Also, the whole city/state data entry is a little...wonky.  It asks for City / state/province, but then pops up a small window for the state afterwards, without any text.
