### ISSUE TITLE
Rename Auto-Reply in mail to Reply and Delete

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#487]
I was looking for a way to reply and then delete mail in one step. Apparently that's waht Auto-Reply does. I think we should rename this to Reply and Delete after sending.

**Comment by wwiv** [comment]
Mail {QSRIDAF?-+GEMZPVUOLCNY@} : ?
(Q)uit to Main Menu
(S)ave Mail and Reply to Author
(R)e-Read Last Mail #
(I)gnore Last Mail Read
(D)elete Last Mail Read
(A)uto-Reply and Delete Last Mail Read

The help text mentions it deletes. What do you want to be different?

**Comment by granitepenguin** [comment]
I think he doesn't like the name "Auto-Reply."  I have to agree that it's a stupid name.  Auto-Reply is unintuitive, but it's likely there because "(R)e-read last Mail" is already using the "R".  

We can't rename it to "Reply and Delete" without breaking the existing letter mnemonic (R) that is already in use.

The basic issue is there are "standard" letters used for certain operations (as defined by how the internet has evolved), and WWIV doesn't use a lot of them the same way.  This is the tip of the iceberg regarding the dated nature of how WWIV menus work in general.  Do we really want to go there?

**Comment by wwiv** [comment]
oh. Yeah, I can't think of a better command key, and there doesn't seem to be a compelling reason to change this command which has been A since 3.0 of wwiv.
