### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#991]
Doors running on local machine do not display to the user but on the wwiv machine it shows running locally but yo have to run it from the machine not from the client.  Doors like doorparty, bbslinks etc work as expected from the connected client.  Not sure mking sense   I can logon from another machine using Netrunner and the doors that are located on the wwiv machine do not display to the remote client.  So they think it is locked up but on the console of the wwiv machine it shows up.  Doors where you connected to another server like doorparty and bbslinks work just fine.

**Comment by granitepenguin** [comment]
I might be seeing the same thing on the linux side.  When testing my TW2002 setup, it looks like it runs but you don't see any output and since I don't have a "local display" to interact with, all I can do is wait for it to time out or kill the session.  I thought it was just something I screwed up, but might actually be the same issue.

**Comment by wwiv** [comment]
turns out that disabling logging also disables doors... sigh

**Comment by wwiv** [comment]
fixed

**Comment by rdfig** [comment]
Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>
